version: "3.1"
services:
  app:
    container_name: affection-x-bot
    build: app
    restart: unless-stopped
    volumes:
      - "./app:/app"
      - "./data:/data"
    command: ['python', 'main.py']
    env_file:
      - ./app/.env